apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - user-service.yaml
  - order-service.yaml
  - user-service-canary.yaml
  - ingress.yaml
  - ingress-canary.yaml
  - network-policies.yaml
  - pdb.yaml
  - vpa.yaml
  - service-monitor.yaml
