apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - user-service
          - order-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
